/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as ProtectRouteImport } from './routes/protect'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as MarketsMarketRouteImport } from './routes/markets.$market'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectRoute = ProtectRouteImport.update({
  id: '/protect',
  path: '/protect',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsMarketRoute = MarketsMarketRouteImport.update({
  id: '/$market',
  path: '/$market',
  getParentRoute: () => MarketsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/markets': typeof MarketsRouteWithChildren
  '/protect': typeof ProtectRoute
  '/transparency': typeof TransparencyRoute
  '/markets/$market': typeof MarketsMarketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/markets': typeof MarketsRouteWithChildren
  '/protect': typeof ProtectRoute
  '/transparency': typeof TransparencyRoute
  '/markets/$market': typeof MarketsMarketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/markets': typeof MarketsRouteWithChildren
  '/protect': typeof ProtectRoute
  '/transparency': typeof TransparencyRoute
  '/markets/$market': typeof MarketsMarketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/markets'
    | '/protect'
    | '/transparency'
    | '/markets/$market'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/markets'
    | '/protect'
    | '/transparency'
    | '/markets/$market'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/markets'
    | '/protect'
    | '/transparency'
    | '/markets/$market'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MarketsRoute: typeof MarketsRouteWithChildren
  ProtectRoute: typeof ProtectRoute
  TransparencyRoute: typeof TransparencyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protect': {
      id: '/protect'
      path: '/protect'
      fullPath: '/protect'
      preLoaderRoute: typeof ProtectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/$market': {
      id: '/markets/$market'
      path: '/$market'
      fullPath: '/markets/$market'
      preLoaderRoute: typeof MarketsMarketRouteImport
      parentRoute: typeof MarketsRoute
    }
  }
}

interface MarketsRouteChildren {
  MarketsMarketRoute: typeof MarketsMarketRoute
}

const MarketsRouteChildren: MarketsRouteChildren = {
  MarketsMarketRoute: MarketsMarketRoute,
}

const MarketsRouteWithChildren =
  MarketsRoute._addFileChildren(MarketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HowItWorksRoute: HowItWorksRoute,
  MarketsRoute: MarketsRouteWithChildren,
  ProtectRoute: ProtectRoute,
  TransparencyRoute: TransparencyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
